# Generated by Django 6.0.5 on 2026-05-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='game_state',
            field=models.CharField(default='LOBBY', max_length=20),
        ),
    ]
