# Generated by Django 6.0.5 on 2026-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_current_round_room_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
